### PR TITLE
Initial commit Open Organisatie helm chart

### LINKED ISSUE #336: Add OpenOrganisatie chart
https://github.com/maykinmedia/open-organisatie

The first Docker image 0.1 has been released and we have our testenvironment rolled out using Ansible. In order to facilitate installing this at Utrecht and Den Haag a helm chart for this new component will be necessary.

For details on how the component works ask @TimdeBeer1

### PR DESCRIPTION
**Pull request by TimdeBeer1**
Fixes #336 

Added helm chart for Open Organisatie

### CODE REVIEW

File: charts/openorganisatie/templates/deployment.yaml [hunk 1]
```diff
@@ -0,0 +1,394 @@
...
+            initialDelaySeconds: {{ .Values.worker.livenessProbe.initialDelaySeconds }}
+            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds }}
+            timeoutSeconds: {{ .Values.worker.livenessProbe.timeoutSeconds }}
+            successThreshold: {{ .Values.worker.livenessProbe.successThreshold }}
+            failureThreshold: {{ .Values.worker.livenessProbe.failureThreshold }}
+          {{- end }}
+          resources:
+            {{- toYaml .Values.worker.resources | nindent 12 }}
+          command:
+            - /celery_worker.sh
```
Comment (SilviaAmAm) [inline charts/openorganisatie/templates/deployment.yaml]: I am getting this error when the celery pods start:
```
{"event": "Signal handler <function receiver_setup_logging at 0x7f790f818f40> raised: TypeError(\"receiver_setup_logging() missing 1 required positional argument: '_format'\")", "exc_info": ["<class 'TypeError'>", "TypeError(\"receiver_setup_logging() missing 1 required positional argument: '_format'\")", "<traceback object at 0x7f79093772c0>"], "source": "app", "timestamp": "2026-01-21T10:44:21.817656Z", "logger": "celery.utils.dispatch.signal", "level": "error"}
```

File: charts/openorganisatie/values.yaml [hunk 2]
```diff
@@ -0,0 +1,391 @@
...
+    ttlSecondsAfterFinished: 0
+    restartPolicy: OnFailure
+    # Note, this field is immutable
+    resources: {}
+  secrets: {}
+  # data: ""
+  # e.g.
+  # data: |-
+  #   oidc_db_config_enable: true
+  #   oidc_db_config_admin_auth:
```
Comment (SilviaAmAm) [inline charts/openorganisatie/values.yaml]: Note: this will not work with version 0.1.0, since mozilla-django-oidc-db was not yet added to the configuration steps:
https://github.com/maykinmedia/open-organisatie/blob/71928fe366a199e571c32e4887a2a4817c8abeac/src/openorganisatie/conf/base.py#L194

Since no other step is added here, with this example configuration it will raise an error!

File: charts/openorganisatie/templates/deployment.yaml (hunk 1 above)
Comment (SilviaAmAm) [reply charts/openorganisatie/templates/deployment.yaml]: Celery is now starting!

File: charts/openorganisatie/templates/configmap.yaml
Comment (SilviaAmAm) [inline charts/openorganisatie/templates/configmap.yaml]: I see from the logs that open organisatie supports open telemetry, but there are not environment variables to configure them. 

Note: we should add these also to the helm starter.

You can have a look for an example of which variables are needed here: https://github.com/maykinmedia/charts/pull/299/changes

**Review by SilviaAmAm — APPROVED** [review]
I still see this warning in the Beat pod logs and the configuration pod:

```
RuntimeWarning: No OTEL_SERVICE_NAME environment variable set, using a default. You should set a (distinct) value for each component (web, worker...)
```
This may need some investigation, but I think that we can merge this for now and then investigate in a different issue.
